#!/bin/sh
# 此脚本旨在通过Husky和lint-staged执行代码的格式化和校验任务。
# 它首先引入了Husky的配置脚本，然后执行pnpm exec lint-staged命令来处理待格式化或校验的文件。

. "$(dirname "$0")/_/husky.sh" # 引入Husky的配置脚本，以便于使用Husky的钩子功能。

pnpm exec lint-staged # 使用pnpm执行lint-staged，lint-staged是一个帮助你对Git暂存区中的文件运行linting任务的工具。
